myapp/views.py
from myapp.forms import (
    AnswerForm,
    DeleteForm,
    RegisterKanjiForm,
    SearchForm,
    SettingForm,
)
from myapp.models import Kanji, transaction
from myapp.utils.answer_formats import make_answer_format

from flask import (
    Blueprint,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    session,
    url_for,
)

bp = Blueprint("app", __name__, url_prefix="")


@bp.route("/")
def home():
    session["score"] = 0
    return render_template("home.html")


@bp.route("/question", methods=["GET", "POST"])
def question():
    form = AnswerForm()
    kanji = Kanji.get_kanji()
    circle = session.get("circle", True)
    if not kanji:
        flash("漢字が見つかりませんでした")
        return redirect(url_for("app.home"))
    if request.method == "POST" and form.validate():
        if form.readings.data == "q":
            session["score"] = 0
            return redirect(url_for("app.question"))
        if form.readings.data == session.get("readings"):
            flash("正解", "success")
            session["score"] = session.get("score", 0) + 1
            if not circle:
                return redirect(url_for("app.question"))
            return redirect(url_for("app.success"))
        else:
            flash("不正解", "danger")
            return redirect(url_for("app.retry"))
    session["kanji_id"] = kanji.id
    session["readings"] = kanji.readings
    time = session.get("time", 8)
    se = session.get("success_sound", False)
    hints_exist = session.get("hints_exist", False)
    gamemode = session.get("review_mode", False)
    score = session.get("score", 0)
    return render_template(
        "kanji_question.html",
        form=form,
        kanji=kanji,
        circle=circle,
        time=time,
        se=se,
        hints_on=hints_exist,
        gamemode=gamemode,
        score=score,
    )


@bp.route("/retry", methods=["GET", "POST"])
def retry():
    form = AnswerForm()
    kanji_id = session.get("kanji_id")
    kanji = Kanji.select_kanji_by_id(kanji_id)
    circle = session.get("circle", True)
    if request.method == "POST" and form.validate():
        if form.readings.data == "q":
            return redirect(url_for("app.question"))
        if form.readings.data == kanji.readings:
            flash("正解", "success")
            session["score"] = session.get("score", 0) + 1
            if not circle:
                return redirect(url_for("app.question"))
            return redirect(url_for("app.success"))
        else:
            flash("不正解", "danger")
            return redirect(url_for("app.retry"))
    time = session.get("time", 8)
    se = session.get("success_sound", False)
    hints_exist = session.get("hints_exist", False)
    gamemode = session.get("review_mode", False)
    score = session.get("score", 0)
    return render_template(
        "kanji_question.html",
        form=form,
        kanji=kanji,
        circle=circle,
        time=time,
        se=se,
        hints_on=hints_exist,
        gamemode=gamemode,
        score=score,
    )


@bp.route("/success", methods=["GET", "POST"])
def success():
    kanji_id = session.get("kanji_id")
    kanji = Kanji.select_kanji_by_id(kanji_id)
    circle = session.get("circle", True)
    time = session.get("time", 8)
    se = session.get("success_sound", False)
    return render_template(
        "kanji_question.html", kanji=kanji, circle=circle, time=time, se=se, suc=True
    )


@bp.route("register_kanji", methods=["GET", "POST"])
def register_kanji():
    form = RegisterKanjiForm(request.form)
    if request.method == "POST" and form.validate():
        kanjis = Kanji(
            kanji=form.kanji.data,
            readings=form.readings.data,
            hints=form.hints.data,
            sp_char=form.sp_char.data,
        )
        from setup import app

        with app.app_context():
            with transaction():
                kanjis.create_new_book()
            flash(f'"{form.kanji.data}"の登録が完了しました。')
        return redirect(url_for("app.register_kanji"))
    session["score"] = 0
    return render_template("kanji_register.html", form=form)


@bp.route("/kanji_delete", methods=["GET", "POST"])
def kanji_delete():
    form = DeleteForm(request.form)
    if request.method == "POST" and form.validate():
        with transaction():
            Kanji.delete_kanji(form.kanji.data)
        flash(f"{form.kanji.data}を削除しました")
        return redirect(url_for("app.register_kanji"))
    session["score"] = 0
    return render_template("kanji_delete.html", form=form)


@bp.route("/search_kanji", methods=["GET"])
def search_kanji():
    form = SearchForm(request.form)
    kanji = request.args.get("kanji", None, type=str)
    kanji_info = Kanji.select_kanji_info_by_kanji(kanji)
    session["score"] = 0
    return render_template("search_kanji.html", form=form, kanji=kanji_info)


@bp.route("/answer_ajax", methods=["GET"])
def answer_ajax():
    kanji_id = request.args.get("kanji_id", -1, type=int)
    failed = request.args.get("failed", -1, type=int)
    if failed == -1:
        return
    if failed == 0:
        session["score"] = 0
    kanji = Kanji.select_kanji_by_id(kanji_id)
    return jsonify(data=make_answer_format(kanji))


@bp.route("/settings", methods=["GET", "POST"])
def settings():
    form = SettingForm(request.form)
    if request.method == "POST" and form.validate():
        flash("設定が更新されました")
        session["circle"] = form.circle.data
        session["time"] = form.next_Q_time.data
        session["success_sound"] = form.success_sound.data
        session["hints_exist"] = form.hints_exist.data
        session["review_mode"] = form.review_mode.data
        return redirect(url_for("app.settings"))
    circle = session.get("circle", True)
    time = session.get("time", 8)
    se = session.get("success_sound", False)
    hints_exist = session.get("hints_exist", False)
    gamemode = session.get("review_mode", False)
    session["score"] = 0
    return render_template(
        "settings.html",
        form=form,
        circle_on=circle,
        time=time,
        se_on=se,
        hints_on=hints_exist,
        gamemode=gamemode,
    )


# @bp.before_request
# def before_request():
#     if request.endpoint not in ['question', 'retry', 'success']:
#         session['score'] = 0


@bp.app_errorhandler(404)
def redirect_main_page(e):
    return redirect(url_for("app.home"))


@bp.app_errorhandler(500)
def server_error(e):
    return render_template("500.html"), 500

myapp/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>{{ field.label }}
    <dd>{{ field(**kwargs)|safe }}
        {% if field.errors %}
        <ul class=errors>
            {% for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </dd>
{% endmacro %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css')}}">
        <link rel="icon" href="{{ url_for('static', filename='icon/kanji_review.png')}}">
        <title>Kanji Review</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{ url_for('app.home') }}">ホーム</a>
            <a class="navbar-brand" href="{{ url_for('app.question') }}">問題</a>
            <a class="navbar-brand" href="{{ url_for('app.register_kanji') }}">登録&削除</a>
            <a class="navbar-brand" href="{{ url_for('app.search_kanji') }}">検索</a>
            <a class="navbar-brand" href="{{ url_for('app.settings') }}">設定</a>
        </nav>
        <div class="jumbotron">
            <h3 align="center">漢字復習</h1>
        </div>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

myapp/templates/home.html
{% extends "base.html" %}
{% block title %}
ホーム - {{ super() }}
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-lg-12 offset-lg-2">
        <h2>メインページ</h2>
        <ul>
            {% for message in get_flashed_messages() %}
            {{ message }}
            {% endfor %}
            <h5>
                <li>「問題」から登録されている漢字の復習ができます。</li>
                <li>「登録&削除」から漢字の登録及び削除が可能です。</li>
                <li>「検索」から登録されている漢字の情報を確認できます。</li>
                <li>「設定」からさまざまな設定ができます。</li>
                <li>「q」で問題をスキップできます。</li>
            </h5>
        </ul>
    </div>
</div>
{% endblock %}
        

myapp/templates/kanji_delete.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
漢字削除 - {{ super() }}
{% endblock %}
{% block content %}
<div class="regist">
    <h2>漢字削除</h2>
    <form method="post">
        {{ form.csrf_token }}
        {{ render_field(form.kanji, autofocus=True, autocomplete="off") }}
        {{ form.submit }}
    </form>
</div>
{% endblock %}

myapp/templates/kanji_question.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
漢字問題 - {{ super() }}
{% endblock %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
<script>
  let kanji_id = "{{ kanji.id }}";
  let q_url = "{{ url_for('app.question') }}";
  let time = "{{ time }}" * 1000;
  let score = "{{ score }}";
  let suc, se, gamemode;
  if ("{{ suc }}" == "True") suc = true;
  else suc = false;
  if ("{{ se }}" == "True") se = true;
  else se = false;
  if ("{{ gamemode }}" == "True") gamemode = true;
  else gamemode = false;
</script>
<script src="{{url_for('static', filename='scripts/answer.js')}}"></script>
<div class="wrap">
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="{{ category }}">{{ message }}</div>
        {% if not form %}
        <img src="{{ url_for('static', filename='images/circle1.png')}}" draggable="false" alt="success">
        {% endif %}
      {% endfor %}
    {% else %}
    <div id="category-blank"></div>
    {% endif %}
  {% endwith %}
  <form id="kanji-form" method="POST" action="">
    {% if form %}
    {{ form.csrf_token }}
    {% endif %}
    <p id="kanji">{{ kanji.kanji }}</p>
    {% if form %}
    <div id="kanjinfo">
      {% if kanji.hints == 'nothing' or not hints_on %}
      <p id="blank"></p>
      {% elif kanji.hints == '地名・建造物' and hints_on %}
      <p id="blds">{{ kanji.hints }}</p>
      {% else %}
      <p id="hints">{{ kanji.hints }}</p>
      {% endif %}
      <p id="answer" name="answer">
        {{ form.readings(autofocus=True, autocomplete="off") }}
      </p>
      {% if kanji.sp_char and hints_on%}
      <p id="special">文字数・読み特殊</p>
      {% else %}
      <p id="blank"></p>
      {% endif %}
    </div>
    {% endif %}
  </form>
</div>
{% endblock %}

myapp/templates/kanji_register.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
漢字登録 - {{ super() }}
{% endblock %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/register.css')}}">
<div class="regist">
    <h1>漢字登録画面</h1>
    {% for message in get_flashed_messages() %}
    {{ message }}
    {% endfor %}
    <form method="POST" autocomplete="off">
        {{ form.csrf_token }}
        {{ render_field(form.kanji) }}
        {{ render_field(form.readings) }}
        {{ render_field(form.hints) }}
        {{ render_field(form.sp_char, checked=False) }}
        {{ form.submit() }}
    </form>
</div>
<div class="delete">
    <a href="{{url_for('app.kanji_delete')}}">
        漢字削除はこちら
    </a>
</div>
{% endblock %}

myapp/templates/search_kanji.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
漢字検索 - {{ super() }}
{% endblock %}
{% block content %}
<div class="jumbotron">
    <p>漢字検索</p>
</div>
<div>
    <div class="col-lg-12">
        <form method="GET">
            {{ form.csrf_token }}
            {{ render_field(form.kanji, autofocus=True, autocomplete="off") }}
            {{ form.submit() }}
        </form>
    </div>
    <div class="col-lg-12">
        {% if kanji %}
        <table class="table">
            <thead>
                <tr>
                    <th>漢字</th>
                    <th>読み方</th>
                    <th>ヒント</th>
                    <th>文字数・読み特殊</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th>{{ kanji.kanji }}</th>
                    <th>{{ kanji.readings}}</th>
                    {% if kanji.hints != 'nothing' %}
                    <th>{{ kanji.hints }}</th>
                    {% else %}
                    <th>なし</th>
                    {% endif %}
                    {% if kanji.sp_char %}
                    <th>◯</th>
                    {% else %}
                    <th>✕</th>
                    {% endif %}
                </tr>  
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

myapp/templates/settings.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
設定 - {{ super() }}
{% endblock %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/settings.css')}}">
<script src="{{ url_for('static', filename='scripts/settings.js')}}"></script>
<div class="regist">
    <h1>設定</h1>
    {% for message in get_flashed_messages() %}
    {{ message }}
    {% endfor %}
    <form method="POST" autocomplete="off">
        {{ form.csrf_token }}
        {{ render_field(form.circle, checked=circle_on) }}
        {{ render_field(form.success_sound, checked=se_on) }}
        {{ render_field(form.hints_exist, checked=hints_on)}}
        {{ render_field(form.next_Q_time, value=time) }}
        {{ render_field(form.review_mode, checked=gamemode)}}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}